"""Vector-API build of the ragged multi-echelon supply chain.

The columnar (``pyomo.contrib.vector``) build of :mod:`bench.models.supply_chain`
-- the *ragged sparse* benchmark the scoping doc (R5) insists the fast path must
handle, and the one linopy/xarray express badly (they must allocate the full
``S*W`` / ``W*R`` grids and mask).

This mirrors the classic model's component **names and index tuples exactly**
(``ship_sw`` over ``SW x periods``, ``ship_wr`` over ``WR x periods``, ``inv``
over ``warehouses x periods``) so the standard-form equivalence oracle can map
the two column spaces by ``(component_local_name, index)``.  Every constraint
family (``wbalance``, ``rdemand``, ``scap``) is expressed as a
:class:`~pyomo.contrib.vector.constraint.VectorConstraint` over the shared
column space ``x = [ship_sw, ship_wr, inv]`` -- the ``assemble`` fast path
requires *all* active constraints to be vectorized, so nothing is left as a
classic ``pyo.Constraint``.

The ragged sparsity lives entirely in the CSR column indices: each constraint
row touches only the lanes incident to that node, built directly as COO->CSR with
no dense grid ever allocated.  The lanes are generated by the same seeded RNG as
the classic model (imported from it), so the two builds are the *same* model.
"""

from __future__ import annotations

from typing import Any, Dict, List

import pyomo.environ as pyo
from pyomo.common.dependencies import numpy as np, scipy

from bench.models import supply_chain as _classic

NAME = "supply_chain"
DESCRIPTION = "Ragged multi-echelon supply chain (vector fast-path build)."
HAS_QUADRATIC = False

SIZES = _classic.SIZES


def _lanes_and_adjacency(params: Dict[str, Any]):
    """Reproduce the classic model's ragged lanes + adjacency (same RNG seed)."""
    import random

    S = int(params["S"])
    W = int(params["W"])
    R = int(params["R"])
    deg = int(params["deg"])
    T = int(params["T"])
    rng = random.Random(int(params.get("seed", 0)))

    warehouses = list(range(W))
    retailers = list(range(R))
    sw = _classic._ragged_lanes(range(S), warehouses, deg, rng)
    wr = _classic._ragged_lanes(range(W), retailers, deg, rng)
    wr_dst = {d for _, d in wr}
    for r in retailers:
        if r not in wr_dst:
            w = rng.randrange(W)
            wr.append((w, r))

    in_to_w: Dict[int, List[int]] = {w: [] for w in warehouses}
    out_from_w: Dict[int, List[int]] = {w: [] for w in warehouses}
    for s, w in sw:
        in_to_w[w].append(s)
    for w, r in wr:
        out_from_w[w].append(r)
    in_to_r: Dict[int, List[int]] = {r: [] for r in retailers}
    for w, r in wr:
        in_to_r[r].append(w)
    out_from_s: Dict[int, List[int]] = {s: [] for s in range(S)}
    for s, w in sw:
        out_from_s[s].append(w)

    return dict(
        S=S,
        W=W,
        R=R,
        T=T,
        warehouses=warehouses,
        retailers=retailers,
        sw=sw,
        wr=wr,
        in_to_w=in_to_w,
        out_from_w=out_from_w,
        in_to_r=in_to_r,
        out_from_s=out_from_s,
    )


def build_pyomo(params: Dict[str, Any]) -> pyo.ConcreteModel:
    d = _lanes_and_adjacency(params)
    S, W, R, T = d["S"], d["W"], d["R"], d["T"]
    warehouses, retailers = d["warehouses"], d["retailers"]
    sw, wr = d["sw"], d["wr"]
    in_to_w, out_from_w = d["in_to_w"], d["out_from_w"]
    in_to_r, out_from_s = d["in_to_r"], d["out_from_s"]

    lane_cap = 100.0
    inv_cap = 500.0
    supply_cap = 2.0 * lane_cap

    from pyomo.contrib.vector import VectorVar, VectorConstraint, VectorObjective

    m = pyo.ConcreteModel(name=f"supply_chain_vec_{S}_{W}_{R}x{T}")
    m.periods = pyo.RangeSet(0, T - 1)
    m.warehouses = pyo.Set(initialize=warehouses)
    m.retailers = pyo.Set(initialize=retailers)
    m.suppliers = pyo.Set(initialize=list(range(S)))
    m.SW = pyo.Set(initialize=sw, dimen=2)
    m.WR = pyo.Set(initialize=wr, dimen=2)

    # Columnar variables -- identical names/index tuples to the classic build.
    m.ship_sw = VectorVar(
        m.SW, m.periods, domain=pyo.NonNegativeReals, bounds=(0, lane_cap)
    )
    m.ship_wr = VectorVar(
        m.WR, m.periods, domain=pyo.NonNegativeReals, bounds=(0, lane_cap)
    )
    m.inv = VectorVar(
        m.warehouses, m.periods, domain=pyo.NonNegativeReals, bounds=(0, inv_cap)
    )
    m.ship_sw.construct()
    m.ship_wr.construct()
    m.inv.construct()

    n_sw = m.ship_sw.n
    n_wr = m.ship_wr.n
    n_inv = m.inv.n
    off_wr = n_sw
    off_inv = n_sw + n_wr
    ncols = n_sw + n_wr + n_inv

    # Position maps (index tuple -> column within the var's block).
    p_sw = {idx: m.ship_sw.position_of(idx) for idx in m.ship_sw._index_set}
    p_wr = {idx: m.ship_wr.position_of(idx) for idx in m.ship_wr._index_set}
    p_inv = {idx: m.inv.position_of(idx) for idx in m.inv._index_set}

    def col_sw(s, w, t):
        return p_sw[(s, w, t)]

    def col_wr(w, r, t):
        return off_wr + p_wr[(w, r, t)]

    def col_inv(w, t):
        return off_inv + p_inv[(w, t)]

    # ---- wbalance: inflow - outflow + prev_inv - inv == 0  (equality) ---- #
    rows_b, cols_b, data_b = [], [], []
    r = 0
    for w in warehouses:
        for t in m.periods:
            for s in in_to_w[w]:
                rows_b.append(r)
                cols_b.append(col_sw(s, w, t))
                data_b.append(1.0)
            for rr in out_from_w[w]:
                rows_b.append(r)
                cols_b.append(col_wr(w, rr, t))
                data_b.append(-1.0)
            if t > 0:
                rows_b.append(r)
                cols_b.append(col_inv(w, t - 1))
                data_b.append(1.0)
            rows_b.append(r)
            cols_b.append(col_inv(w, t))
            data_b.append(-1.0)
            r += 1
    nb = r
    A_b = scipy.sparse.coo_matrix((data_b, (rows_b, cols_b)), shape=(nb, ncols)).tocsr()

    # ---- rdemand: sum ship_wr[w,r,t] == demand(r,t)  (equality) --------- #
    def demand(r_, t_):
        return 5.0 + ((r_ * 3 + t_) % 7)

    rows_d, cols_d, data_d, b_d = [], [], [], []
    r = 0
    for rr in retailers:
        for t in m.periods:
            for w in in_to_r[rr]:
                rows_d.append(r)
                cols_d.append(col_wr(w, rr, t))
                data_d.append(1.0)
            b_d.append(demand(rr, t))
            r += 1
    nd = r
    A_d = scipy.sparse.coo_matrix((data_d, (rows_d, cols_d)), shape=(nd, ncols)).tocsr()

    # ---- scap: sum ship_sw[s,w,t] <= supply_cap  (inequality) ---------- #
    rows_c, cols_c, data_c = [], [], []
    r = 0
    for s in range(S):
        for t in m.periods:
            for w in out_from_s[s]:
                rows_c.append(r)
                cols_c.append(col_sw(s, w, t))
                data_c.append(1.0)
            r += 1
    nc = r
    A_c = scipy.sparse.coo_matrix((data_c, (rows_c, cols_c)), shape=(nc, ncols)).tocsr()

    xvars = [m.ship_sw, m.ship_wr, m.inv]
    m.wbalance = VectorConstraint(A=A_b, x=xvars, rhs=np.zeros(nb))
    m.rdemand = VectorConstraint(A=A_d, x=xvars, rhs=np.asarray(b_d, dtype=float))
    m.scap = VectorConstraint(A=A_c, x=xvars, ub=np.full(nc, supply_cap))
    m.wbalance.construct()
    m.rdemand.construct()
    m.scap.construct()

    # ---- objective: lane costs + inventory holding ---------------------- #
    sw_cost = {(s, w): 1.0 + ((s + w) % 5) for (s, w) in sw}
    wr_cost = {(w, r): 1.0 + ((w + r) % 4) for (w, r) in wr}
    c_sw = np.empty(n_sw, dtype=float)
    for (s, w, t), pos in p_sw.items():
        c_sw[pos] = sw_cost[(s, w)]
    c_wr = np.empty(n_wr, dtype=float)
    for (w, rr, t), pos in p_wr.items():
        c_wr[pos] = wr_cost[(w, rr)]
    c_inv = np.full(n_inv, 0.05, dtype=float)

    m.obj = VectorObjective(
        terms={m.ship_sw: c_sw, m.ship_wr: c_wr, m.inv: c_inv}, sense=pyo.minimize
    )
    m.obj.construct()
    return m
